### ISSUE TITLE
Tidak bisa start npm

### ISSUE THREAD

**Issue by MomodKASKUS** [mhrdwan/warpcast-bot-multi-akun#1]
error saat inpit command " npm start "
padahal sudah buka di direktori warpcast-bot-multi-akun

`Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fauzan/.npm/_logs/2024-02-24T07_53_02_883Z-debug-0.log`

**Comment by mhrdwan** [comment]
pakai command

node index.js
